algorithm-studyy/algorithm

jiwon/programmers/lifeboat.py

프로그래머스 구명보트

---

jiwon/programmers/expected_tournament.py

생각보다 쉽게 풀 수 있었는데 직관적으로 생각하는 것도 길러야할듯..

프로그래머스 예상 대진표

---

jiwon/programmers/discount_event.py

카운터를 쓰자 
from collections import Counter

프로그래머스 할인 행사

---

jiwon/programmers/2xn_tiling.py

프로그래머스 2xn 타일링

---

jiwon/programmers/check_math_multiple.py
jiwon/programmers/find_prime_number.py

문제 링크 : https://school.programmers.co.kr/learn/courses/30/lessons/42839
1. 제한 사항의 개수가 작았기 때문에 모든 경우의 수를 생각했음
2. 구현을 쉽게 하기 위해 Permutations으로 구현했고,
3. 나머지를 소수를 구할 때 number의 루트 + 1로 최대를 정해 시간 복잡도를 줄이려고 했음

프로그래머스 소수 찾기

---

jiwon/programmers/check_distance.py

1. 모든 경우의 수를 찾는다.
2. if문으로 모두 찾는다.

프로그래머스 거리두기

---

jiwon/programmers/check_math_multiple.py
jiwon/programmers/delivery.py
jiwon/programmers/find_prime_number.py

DFS로 풀었을 때 계속 시간초과가 나서 
다익스트라 공부해서 풀어보기

[다시풀기] 프로그래머스 배달

---

SeongYeon/js/programmers/archeryContest(failed).js
SeongYeon/js/programmers/nQueen(failed).js

https://school.programmers.co.kr/learn/courses/30/lessons/92342

프로그래머스 양궁대회 (실패!)

---

SeongYeon/js/programmers/nQueen(failed).js

실수로 이전에 올렸던 풀리퀘에다가 이 문제까지 같이 푸시해버려서;;
이전꺼 머지시키고 새로 풀리퀘 올렸슴당

N-Queen 실패

---

JiHwan/programmers/do_homework.py
JiHwan/programmers/escaped_maze.py
JiHwan/programmers/rectangle.py

아직 코드르 다 짜진 못했고 for 문 안에서 if문을 사용해서 시작시간과 걸리는 시간의 합을 사용하여 그 다음 과제의 시작 시간보다 작으면 answer에 append  시작 시간보다 크면 not_yet에 저장을 한 후  과제를 끝낸 후 다음 과제 시작 시간 까지 시간이 남아있을 때 not_yet에서 pop 해서 과제 수행..
PR 적다가 생각난 사항 : not_yet에서 pop을 하고 걸리는 시간을 어떻게 활용해야할까?? 라는 의문이....

 과제 진ã행하기 진행중

---

jiwon/programmers/python/find_maximum_squre.py

시간 복잡도 생각하기 
무턱 대고 DFS, BFS 쓰지 말기

프로그래머스 가장 큰 정사각형 찾기

---

JiHwan/programmers/how_to_line.py
JiHwan/programmers/table_hash_func.py

줄바꾸기는 아직 해결을 못했지만 오늘 푼 해쉬테이블은 해결했다.

줄 바꾸기 진행 중

---

jiwon/programmers/python/defense_game.py

프로그래머스 디펜스 게임

---

jiwon/leetcode/344. Reverse String.py
jiwon/leetcode/937. Reorder Data in Log Files.py

LeetCode 344, 937

---

JiHwan/leetcode/most_common_word.py
JiHwan/leetcode/reorder_data_in_logs_flies.py
JiHwan/leetcode/reverse_list.py
JiHwan/programmers/escaped_maze.py

리트코드 344, 937

---

JiHwan/leetcode/Longest_Palindromic_Substring.py
JiHwan/leetcode/anagrams.py
JiHwan/leetcode/most_common_word.py
JiHwan/leetcode/two_sum.py

doing anagrams

---

JiHwan/leetcode/121. Best Time to Buy and Sell Stock.py
JiHwan/leetcode/234. Palindrome Linked List.py

이중포문을 사용하니까 시간초과 발생 maxsize를 사용해서 단일 포문으로 할 수 있도록 변경

---

.idea/misc.xml
JiHwan/programmers/programmers_highscore_kit/min_square.py

구하니 오류가 났다. 이후에 가로 세로 서로 중에서 더 큰 수는 w에 작은
수는 h에 저장하여 w와h의 최대의 곱을 return 하도록 하였다.

처음에는 최대와 최소를 구분하지 않고 가로와 세로만 곱해서 그 값의 최소를

---

jiwon/programmers/python/enforcement_camera.py
jiwon/programmers/python/number_game.py

숫자 게임의 경우 그리디하게 푸는 것이 시간 복잡도가 더 좋음 O(nlogn)

프로그래머스 숫자 게임, 단속 카메라

---

jiwon/programmers/python/install_station.py

프로그래머스 기지국 설치

---

jiwon/programmers/python/bad_user.py
jiwon/programmers/python/gem_shopping.py

프로그래머스 불량사용자, 보석쇼핑

---

jiwon/programmers/python/connecting_island.py

섬 연결하기 해결.. (프림)

---

jiwon/boj/boj_java/Boj1475.java
jiwon/boj/boj_java/Boj3273.java
jiwon/boj/boj_java/Template.java
jiwon/boj/python/1475.py
jiwon/boj/python/3273.py

백준 배열 문제 풀이

---

jiwon/.idea/compiler.xml
jiwon/boj/boj_java/Boj5397.java
jiwon/boj/python/5397.py
jiwon/boj/python/test.py

백준 5397 키로거

---

jiwon/boj/boj_java/Boj4949.java
jiwon/boj/python/2504.py
jiwon/boj/python/4949.py

백준 균형잡힌 세상

---

JiHwan/BJ/boj_java/src/Boj1021.java
JiHwan/BJ/boj_java/src/Boj2577.java
JiHwan/BJ/boj_java/src/Template.java

지원이형 따라서 자바 설정 및 문제하나 해결

---

.idea/misc.xml

not solved

---

jiwon/boj/python/insert_operand.py
jiwon/programmers/python/receive_report_result.py

프로그래머스 신고결과 받기

---

JiHwan/BJ/11501.py
JiHwan/BJ/4659.py

11501 solve

---

.idea/misc.xml
JiHwan/BJ/15649_2.py
JiHwan/BJ/15650_2.py
JiHwan/BJ/15651_2.py
JiHwan/BJ/15652_2.py
JiHwan/BJ/15654_2.py
JiHwan/BJ/15655.py
JiHwan/BJ/15656.py
JiHwan/BJ/15657.py

n과m 9까지 완료
